- title: "KSL's Community Trail 3 Mile"
  description: "Coming soon..."
  image: "/assets/images/route-ksl-community-trail-3mi.png"
  strava_url: "https://www.strava.com/routes/3469063649265790306"
- title: "KSL's Community Trail 4 Mile"
  description: "Coming soon..."
  image: "/assets/images/route-ksl-community-trail-4mi.png"
  strava_url: "https://www.strava.com/routes/3469063649264538978"
- title: "KSL's Community Trail 5 Mile"
  description: "Coming soon..."
  image: "/assets/images/route-ksl-community-trail-5mi.png"
  strava_url: "https://www.strava.com/routes/3469064585607511044"
- title: "AF's Community Trail 3 Mile"
  description: "We take the community trail down and loop back on 108 to return to the Brick, or optionally take the community trail back."
  image: "/assets/images/route-af-community-trail-3mi.png"
  strava_url: "https://www.strava.com/routes/3386033820720211046"
- title: "AF's Community Trail 5 Mile"
  description: "We take the community trail down and loop around the Dover High School, and follow 108 back to the Brick, or optionally take the community trail back."
  image: "/assets/images/route-af-community-trail-5mi.png"
  strava_url: "https://www.strava.com/routes/3386034544269733974"