- title: "KSL Community Trail 3 Mile"
  description: "Coming soon..."
  image: "/assets/images/route-ksl-community-trail-3mi.png"
  strava_url: "https://www.strava.com/routes/3469063649265790306"
- title: "KSL Community Trail 4 Mile"
  description: "Coming soon..."
  image: "/assets/images/route-ksl-community-trail-4mi.png"
  strava_url: "https://www.strava.com/routes/3469063649264538978"
- title: "KSL Community Trail 5 Mile"
  description: "Coming soon..."
  image: "/assets/images/route-ksl-community-trail-5mi.png"
  strava_url: "https://www.strava.com/routes/3469064585607511044"
