- title: "Mt. Vernon 3 Mile"
  description: "From Orchard: right on Chestnut, left on Sixth, right on Mt. Vernon, left on Roosevelt, right on Horne, left on Glenwood, left on Whittier, left on Sixth, right on Central, right on Orchard back to The Brick."
  image: "/assets/images/route-mt-vernon-3mi.png"
  strava_url: "https://www.strava.com/routes/3470393654892154882"
- title: "Mt. Vernon 4 Mile"
  description: "From Orchard: right on Chestnut, left on Sixth, right on Mt. Vernon, left on Roosevelt, right on Horne, left on Glenwood. Instead of turning on Whittier, stay straight on Glenwood to Sixth. Left on Sixth, right on Central, right on Orchard back to The Brick."
  image: "/assets/images/route-mt-vernon-4mi.png"
  strava_url: "https://www.strava.com/routes/3470393007597569096"
- title: "Mt. Vernon 5 Mile"
  description: "Start the same as the 4-mile route through Glenwood and Sixth. Instead of heading directly to Central, right on Whittier, left on Washington, left on Chestnut, right on Orchard back to The Brick. (Same as Washington Reversed)"
  image: "/assets/images/route-mt-vernon-5mi.png"
  strava_url: "https://www.strava.com/routes/3470389449535007884"
- title: "Washington 3 Mile"
  image: "/assets/images/route-washington-3mi.png"
  strava_url: "https://www.strava.com/routes/3470390446742721608"
  description: "pending..."
- title: "Washington 4 Mile"
  image: "/assets/images/route-washington-4mi.png"
  strava_url: "https://www.strava.com/routes/3470396528850932808"
  description: "pending..."
- title: "Washington 5 Mile"
  image: "/assets/images/route-washington-5mi.png"
  strava_url: "https://www.strava.com/routes/3470390446748039240"
  description: "From Orchard Street, head up to turn left on Chestnut, then right on Washington and all the way out to a right on Whittier. Head up to take a left on Sixth Street at the light, and follow that until Glenwood Ave, where you take a right. Continue on Glenwood until taking a right on Horne Street, then a left on Roosevelt across from the school. After climbing Roosevelt, take a right on Mt. Vernon and follow that all the way back to Sixth, where you take a left and then a right on to Central, which you take back to the starting point for about 5 miles."
- title: "Red's 3 Mile"
  image: "/assets/images/route-reds-3mi.png"
  strava_url: "https://www.strava.com/routes/3470392330993964104"
  description: "From Orchard: right on Central crossing the intersection, follow Central to Court. Left on Court and split left at the cemetery on to Back Rd. Follow Back Rd to Henry Law. At the bottom of Henry Law hill, take a right on to Payne St. and take a left when you reach the river onto Washington. Follow Washington back to the intersection with Central, taking a right on Central and back to Orchard and The Brick."
- title: "Red's 5 Mile"
  image: "/assets/images/route-reds-5mi.png"
  strava_url: "https://www.strava.com/routes/3470388515299698690"
  description: "From Orchard: same as the 3-mile route but instead of splitting left at the cemetery, split right onto Middle Rd. Follow Middle Rd to the end and take a left onto Back Rd. Follow Back Rd to Henry Law, and follow Henry Law until it meets back at the intersection of Washington and Central. Cross the intersection following Central, and back to Orchard and The Brick."